services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - BASE_URL=http://127.0.0.1:8080/
      - INSTANCE_NAME=searxng
    restart: unless-stopped
